version: '3.8'
services:
  app:
    build: .
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/sobertrip
      - MAP_API_URL=http://map-service
  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
