services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 1drive-trip-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/trip
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8080}
    depends_on:
      - mongodb
    networks:
      - trip-network

  mongodb:
    image: mongo:7.0
    container_name: trip-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - trip-network

networks:
  trip-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
