export enum TripStatus {
  DRAFT = 'DRAFT',
  WAITING_FOR_DRIVER = 'WAITING_FOR_DRIVER',
  DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',
  APPROVED = 'APPROVED',
  DRIVER_ON_WAY = 'DRIVER_ON_WAY',
  PICK_UP_ON_WAY = 'PICK_UP_ON_WAY',
  PAYMENT = 'PAYMENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
